version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: property_platform_db
    environment:
      POSTGRES_DB: property_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - property_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: property_platform_backend
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/property_platform
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - property_network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: property_platform_frontend
    environment:
      - VITE_API_URL=http://localhost:3001
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - property_network
    command: npm run dev

volumes:
  postgres_data:

networks:
  property_network:
    driver: bridge 